accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

calendarapp/urls.py
from django.urls import path

from . import views

app_name = "calendarapp"


urlpatterns = [
    path("", views.CalendarView.as_view(), name="calendar"),
    path("evaluation/", views.OverviewView.as_view(), name="overview"),
    path("event/new/", views.EventModalCreateView.as_view(), name="event"),
    path(
        "event/new/<str:date>/",
        views.EventModalCreateView.as_view(),
        name="event_create",
    ),
    path(
        "event/details/<int:pk>/",
        views.EventDetailsModalUpdateView.as_view(),
        name="event_details",
    ),
    path(
        "event/edit/<int:pk>/",
        views.EventEditModalUpdateView.as_view(),
        name="event_edit",
    ),
    path(
        "event/post_edit/<int:pk>/",
        views.EventPostEditModalUpdateView.as_view(),
        name="event_post_edit",
    ),
    path(
        "event/remove/<int:pk>/",
        views.EventDeleteModalUpdateView.as_view(),
        name="event_delete",
    ),
    path(
        "eventcategory/new/",
        views.EventCategoryCreateView.as_view(),
        name="eventcategory_create",
    ),
    path("all-events-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "upcoming-events-list/",
        views.UpcomingEventsListView.as_view(),
        name="upcoming_events",
    ),
    path("exercises-list/", views.AllExercisesListView.as_view(), name="exercises"),
    path("exercise/new/", views.ExerciseModalCreateView.as_view(), name="exercise"),
]

calendarapp/models/event_abstract.py
from django.db import models


class EventAbstract(models.Model):
    """Event abstract model. Adds meta fields to events."""

    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_post = models.BooleanField(
        default=False
    )  # 'is_post' is true when an event has been updated with feedback after occurring

    class Meta:
        abstract = True

calendarapp/models/event_category.py
from django.db import models


class EventCategoryManager(models.Manager):
    """EventCategory manager"""
    
    def get_parent_categories(self):
        """Gets all parent categories. These are defined as itself having a parent category."""
        parent_categories = EventCategory.objects.filter(parent_category__isnull=True)
        return parent_categories

    def get_categories(self):
        """Gets all categores. These are defined as having a parent category."""
        categories = EventCategory.objects.exclude(parent_category__isnull=True)
        return categories


class EventCategory(models.Model):
    """EventCategory model"""

    name = models.CharField(max_length=256, unique=True)
    parent_category = models.ForeignKey(
        'self', related_name='categories',
        on_delete=models.SET_NULL, blank=True, null=True,
    )

    objects = EventCategoryManager()

    def __str__(self):
        return self.name

calendarapp/models/exercise_category.py
from django.db import models


class ExerciseCategory(models.Model):
    """ExerciseCategory model"""

    name = models.CharField(max_length=256, unique=True)

    def __str__(self):
        return self.name

calendarapp/views/calendar_views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from datetime import datetime

from calendarapp.models import Event


class CalendarView(LoginRequiredMixin, generic.View):
    """The main calendar view."""

    login_url = "accounts:signin"
    template_name = "calendarapp/calendar.html"

    def get(self, request, *args, **kwargs):
        """Gets all events from the currently signed in user to display in the FullCalendar."""
        events = Event.objects.get_all_events(user=request.user)
        event_list = []
        for event in events:
            event_list.append(
                {
                    "event_pk": event.pk,
                    # url's are added so they can be used in Bootstrap Modal Forms from the calendar template
                    "url_details": reverse(
                        "calendarapp:event_details", kwargs={"pk": event.pk}
                    ),
                    "url_edit": reverse(
                        "calendarapp:event_edit", kwargs={"pk": event.pk}
                    ),
                    "url_delete": reverse(
                        "calendarapp:event_delete", kwargs={"pk": event.pk}
                    ),
                    "parent_category": event.category.parent_category.name,  # used for adding CSS classes
                    "title": event.title,
                    "description": event.description,
                    "allDay": int(
                        event.all_day
                    ),  # uses int() so that the boolean gets translated to JS boolean (0/1)
                    "start": event.start_datetime.strftime("%Y-%m-%dT%H:%M:%S"),
                    "end": event.end_datetime.strftime("%Y-%m-%dT%H:%M:%S"),
                    "planned_exertion": event.planned_exertion,  # used for adding CSS classes
                }
            )
        rand = int(datetime.now().strftime("%Y%m%d"))
        context = {"events": event_list, "rand": rand}
        return render(request, self.template_name, context)

calendarapp/views/event_list.py
from django.views.generic import ListView

from datetime import datetime

from calendarapp.models import Event


class AllEventsListView(ListView):
    """All events list view."""

    template_name = "calendarapp/events_list.html"
    model = Event

    def get_queryset(self):
        return Event.objects.get_all_events(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rand"] = int(datetime.now().strftime("%Y%m%d"))
        return context


class UpcomingEventsListView(ListView):
    """Upcoming events list view."""

    template_name = "calendarapp/events_list.html"
    model = Event

    def get_queryset(self):
        return Event.objects.get_upcoming_events(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rand"] = int(datetime.now().strftime("%Y%m%d"))
        return context

calendarapp/views/event_views.py
import calendar
from datetime import date, datetime, time, timedelta

from bootstrap_modal_forms import generic as bsmfg
from django.core import serializers
from django.urls import reverse_lazy
from django.views import generic

from calendarapp.forms import EventDetailsModalForm, EventModalForm
from calendarapp.models import Event, EventCategory


class EventModalCreateView(bsmfg.BSModalCreateView):
    """Event create view with Bootstrap Modal CreateView."""

    template_name = "calendarapp/event.html"
    form_class = EventModalForm
    success_url = reverse_lazy("calendarapp:calendar")

    def form_valid(self, form):
        """Adds additional checks to determine the form validity."""
        self.object = form.save(commit=False)
        self.object.user = (
            self.request.user
        )  # Gets the user from the request and sets it as the object.user

        # If no start_time is inputted, derives that the event is an allDay event
        # and fills the missing fields with the appopriate data
        if self.object.start_time is None:
            self.object.all_day = True
            self.object.start_time = time(0, 0, 0, 0)
            self.object.end_time = time(0, 0, 0, 0)

        # If no end_date is inputted, derives that the event ends on the start_date
        # and fills the end_date with the inputted start_date
        if self.object.end_date is None:
            self.object.end_date = self.object.start_date

        # Combines the inputted date and time to datetimes for start and end
        self.object.start_datetime = datetime.combine(
            self.object.start_date, self.object.start_time
        )
        self.object.end_datetime = datetime.combine(
            self.object.end_date, self.object.end_time
        )

        return super().form_valid(form)

    def get_form_kwargs(self):
        """Adds the <date> from the form url to the form kwargs"""
        kwargs = super(EventModalCreateView, self).get_form_kwargs()
        # self.kwargs holds all the kwargs of the view
        date = datetime.strptime(self.kwargs["date"], "%Y-%m-%d").date()
        kwargs.update({"date": date})
        return kwargs

    def get_context_data(self, **kwargs):
        """Adds categories and parent categories to the context of the view."""
        context = super().get_context_data(**kwargs)

        parent_categories = EventCategory.objects.get_parent_categories()
        categories = serializers.serialize(
            "json", EventCategory.objects.get_categories()
        )  # serialize as json so JS can unpack it

        context.update(
            {
                "parent_categories": parent_categories,
                "categories": categories,
            }
        )

        return context


class EventEditModalUpdateView(bsmfg.BSModalUpdateView):
    """Event edit view with Bootstrap Modal UpdateView."""

    model = Event
    template_name = "calendarapp/event_edit.html"
    form_class = EventModalForm
    success_url = reverse_lazy("calendarapp:calendar")

    def form_valid(self, form):
        """Adds additional checks to determine the form validity."""
        self.object = form.save(commit=False)

        # If no start_time is inputted, derives that the event is an allDay event
        # and fills the missing fields with the appopriate data
        if self.object.start_time is None:
            self.object.all_day = True
            self.object.start_time = time(0, 0, 0, 0)
            self.object.end_time = time(0, 0, 0, 0)

        # If no end_date is inputted, derives that the event ends on the start_date
        # and fills the end_date with the inputted start_date
        if self.object.end_date is None:
            self.object.end_date = self.object.start_date

        # Combines the inputted date and time to datetimes for start and end
        self.object.start_datetime = datetime.combine(
            self.object.start_date, self.object.start_time
        )
        self.object.end_datetime = datetime.combine(
            self.object.end_date, self.object.end_time
        )

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """Adds categories and parent categories to the context of the view."""
        context = super().get_context_data(**kwargs)

        now = datetime.now()

        parent_categories = EventCategory.objects.get_parent_categories()
        categories = serializers.serialize(
            "json", EventCategory.objects.get_categories()
        )  # serialize as json so JS can unpack it

        context.update(
            {
                "now": now,
                "parent_categories": parent_categories,
                "categories": categories,
            }
        )

        return context


class EventDetailsModalUpdateView(bsmfg.BSModalUpdateView):
    """Event details view with Bootstrap Modal UpdateView. Allows the user to see the details of an existing event
    but also allows them to submit feedback when the event has occurred; this requires the view to be an UpdateView.
    """

    model = Event
    template_name = "calendarapp/event_details.html"
    form_class = EventDetailsModalForm
    success_url = reverse_lazy("calendarapp:calendar")

    def form_valid(self, form):
        """When feedback is submitted, changes the is_post value to True."""
        self.object = form.save(commit=False)
        self.object.is_post = True
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """Adds additional context."""
        context = super().get_context_data(**kwargs)

        now = (
            datetime.now()
        )  # Used in templates to determine if an event is past or future

        last_five_events = Event.objects.get_last_five_events(
            user=self.request.user, category=self.object.category
        )

        context.update({"now": now, "last_events": last_five_events})

        return context


class EventPostEditModalUpdateView(bsmfg.BSModalUpdateView):
    """Event edit view with Bootstrap Modal UpdateView where the event.is_post=True. Allows the user to edit an event
    when they have already submitted feedback before."""

    model = Event
    template_name = "calendarapp/event_post_edit.html"
    form_class = EventDetailsModalForm
    success_url = reverse_lazy("calendarapp:calendar")

    def form_valid(self, form):
        """When feedback is submitted, changes the is_post value to True."""
        self.object = form.save(commit=False)
        self.object.is_post = True
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """Adds additional context."""
        context = super().get_context_data(**kwargs)

        now = (
            datetime.now()
        )  # Used in templates to determine if an event is past or future
        context["now"] = now

        return context


# class EventDeleteModalUpdateView(generic.UpdateView):
#     """Event delete view with Bootstrap Modal UpdateView. Instead of a normal DeleteView, this UpdateView allows
#     the user to update the 'is_deleted' field of an event."""

#     model = Event
#     template_name = "calendarapp/event_delete.html"
#     fields = ["is_deleted"]
#     success_url = reverse_lazy("calendarapp:calendar")

#     def form_valid(self, form):
#         """When the form is submitted, changes the event field 'is_deleted' to True."""
#         self.object = form.save(commit=False)
#         # self.object.is_deleted = True
#         self.object.delete()
#         return super().form_valid(form)


class EventDeleteModalUpdateView(bsmfg.BSModalDeleteView):
    model = Event
    template_name = "calendarapp/event_delete.html"
    success_message = "Success: Event was deleted."
    success_url = reverse_lazy("calendarapp:overview")

calendarapp/views/exercises_views.py
from datetime import datetime

from bootstrap_modal_forms import generic as bsmfg
from django.urls import reverse_lazy
from django.views.generic import ListView

from calendarapp.forms import ExerciseModalForm
from calendarapp.models import Exercise


class AllExercisesListView(ListView):
    """All exercises list view."""

    template_name = "calendarapp/exercises.html"
    model = Exercise

    def get_queryset(self):
        return Exercise.objects.group_exercises(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rand"] = int(datetime.now().strftime("%Y%m%d"))
        context["excluded_exercises"] = ""
        return context


class ExerciseModalCreateView(bsmfg.BSModalCreateView):
    """Event create view with Bootstrap Modal CreateView."""

    template_name = "calendarapp/exercise.html"
    form_class = ExerciseModalForm
    success_url = reverse_lazy("calendarapp:exercises")

    def form_valid(self, form):
        """Adds additional checks to determine the form validity."""
        self.object = form.save(commit=False)
        self.object.user = (
            self.request.user
        )  # Gets the user from the request and sets it as the object.user

        return super().form_valid(form)

calendarapp/views/other_views.py
from django.views.generic import View, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy

from datetime import timedelta, datetime, date
import calendar

from calendarapp.models import Event, EventCategory
from calendarapp.forms import EventCategoryForm


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split("-"))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = "month=" + str(prev_month.year) + "-" + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = "month=" + str(next_month.year) + "-" + str(next_month.month)
    return month


class OverviewView(LoginRequiredMixin, View):
    """Simple view that contains all post events from the user."""

    login_url = "accounts:signin"
    template_name = "calendarapp/overview.html"

    def get(self, request, *args, **kwargs):
        post_events = Event.objects.get_post_events(user=request.user)
        rand = int(datetime.now().strftime("%Y%m%d"))
        context = {
            "post_events": post_events,
            "rand": rand,
        }
        return render(request, self.template_name, context)


class EventCategoryCreateView(CreateView):
    """EventCategory create view."""

    template_name = "calendarapp/eventcategory_create.html"
    form_class = EventCategoryForm
    success_url = reverse_lazy('calendarapp:calendar')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rand'] = int(datetime.now().strftime("%Y%m%d"))
        return context

templates/calendarapp/calendar.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Calendar | {% endblock title %}

{% block extracss %}
  <link rel="stylesheet" type="text/css" href="{% static 'calendar/main.css' %}?r={{ rand }}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}?r={{ rand }}">
{% endblock extracss %}

{% block content %}
<div class="row tile px-md-3">
  <div class="w-100 px-md-3">
    <div id="calendar"></div>
  </div>
</div>

<div class="modal fade" id="eventModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" style="overflow-y: initial;" role="document">
      <div class="modal-content">
      </div>
  </div>
</div>
{% endblock content %}

{% block extrascripts %}
  <script src="{% static 'calendar/main.js' %}"></script>
  <script>
    // Helper function for adding days to a given date
    function addDays(date, days) {
      var result = new Date(date);
      result.setDate(result.getDate() + days);
      return result;
    };

    // Loads the FullCalendar on page load
    document.addEventListener('DOMContentLoaded', function() {
      var calendarEl = document.getElementById('calendar');
      var today = new Date();

      var calendar = new FullCalendar.Calendar(calendarEl, {
        customButtons: {
          // Button for adding a new event with the current date using a bootstrap modal
          addEvent: {
            text: "Add",
            icon: "plus-square",
            click: function() {
              var day = today.getFullYear().toString().padStart(2, '0') + '-' + (today.getMonth()+1).toString().padStart(2, '0') + '-' + today.getDate().toString().padStart(2, '0')
              $(this).modalForm({
                modalID: "#eventModal",
                formURL: "{% url 'calendarapp:event' %}" + day + "/",
              })
            }
          }
        },
        height: 780,
        headerToolbar: {
          start: 'prev,next today addEvent',
          center: 'title',
          end: 'dayGridMonth,timeGridWeek,timeGridDay'
        },
        initialDate: today,
        firstDay: 1,
        navLinks: false,
        eventDisplay: 'block',
        eventTimeFormat: {
          hour: '2-digit',
          minute: '2-digit',
          hour12: false
        },
        eventClassNames: function(arg) {
          // Adding classes to the event fc-event-custom and dynamically based on its extended properties
          var classes = [arg.event.extendedProps['parent_category'].toLowerCase(), 
          "planned_exertion_" + arg.event.extendedProps['planned_exertion'],
          'fc-event-custom']
          return classes
        },
        eventMouseEnter: function(mouseEnterInfo) {
          // Adding a hover class on enter
          mouseEnterInfo.el.classList.toggle("custom-hover")
        },
        eventMouseLeave: function(mouseLeaveInfo) {
          // Removing a hover class on exit
          mouseLeaveInfo.el.classList.toggle("custom-hover")
        },
        dateClick: function (info) {
          // On clicking a date, adding a modal form for creating an event to the top of the daygrid
          var day = info.dayEl.getAttribute("data-date")
          var el = info.dayEl.getElementsByClassName("fc-daygrid-day-top")[0]
          $(el).modalForm({
              modalID: "#eventModal",
              formURL: "{% url 'calendarapp:event' %}" + day + "/",
          })
        },
        eventClick: function(info) {
          // On clicking an event, adding a modal form for viewing the event details to the event
          info.jsEvent.preventDefault() // Prevents the default behavior of navigating to a different url
          var el = info.el
          var url = info.event.extendedProps['url_details']
          $(el).modalForm({
              modalID: "#eventModal",
              formURL: url,
          })
        },
        dayMaxEvents: true, // Shows "more" when there are too many events to show
        events: {{ events|safe }}, // Gets all the events via the events template tag
        eventDataTransform: function(eventData) {
          if (eventData.allDay) {
            // Adds a day to an event if its an allDay event, otherwise it shows a day short
            var d = new Date(eventData.end)
            eventData.end= addDays(d, 1)
          }
        },
      });

      calendar.render();
    });
  </script>
{% endblock extrascripts %}

templates/calendarapp/event.html
<form method="post" action="">
  {% csrf_token %}

 <div class="modal-header bg-primary">
    <h5 class="modal-title text-white">Create Event</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body" style="height: 80vh; overflow-y: auto;">
    <div class="form-group">
      {{ form.title }}
    </div>
    <!-- Date and time form fields; toggling all fields (except start date) with JS functions below -->
    <div class="form-group form-row" style="margin-left: 0px;">
      <span>{{ form.start_date }}</span><span class="form-field-hideable form-field-hide">&nbsp;&nbsp;&nbsp;</span><span class="form-field-hideable form-field-hide">{{ form.start_time }}</span>
      <span style="font-size: 1.5rem;">&nbsp;-&nbsp;</span>
      <span class="form-field-hideable">{{ form.end_date }}</span><span class="form-field-hideable form-field-hide">{{ form.end_time }}</span>
      <button id="add-time" type="button" class="btn btn-default" style="margin-left: 5px;">Add time</button>
    </div>
    <div id="all-day" class="form-group form-field-hide">
      {{ form.all_day }} All day
    </div>
    <!-- Shows a first select element with all available parent categories and adds a 'new category' option -->
    <div class="form-group">
      <select name="parent_category" class="form-control" id="id_parent_category">
        <option value=""></option>
        {% for parent_category in parent_categories %}
          <option value="{{ parent_category.pk }}">{{ parent_category }}</option>
        {% endfor %}
        <!-- Adding a new category option; if selected, opens the eventcategory_create url through JS function below -->
        <option id="new_category" value="{% url 'calendarapp:eventcategory_create' %}">Add new category:</option>
      </select>
    </div>
    <div class="form-group">
      {{ form.category }}
    </div>
    <div id="planned_exertion" class="form-group form-control">
      <h6 class="d-inline align-middle" style="margin-right: 10px;">Planned exertion</h6>{{ form.planned_exertion }}
    </div>
    <div class="form-group">
      {{ form.description }}
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create</button>
  </div>

</form>

<script>
  // Function to toggle the form-field-hide class for the add-time button (hides) and all-day checkbox (shows)
  // and on all elements with form-field-hideable class, adds the function to the add-time button
  function hideFuncOne() {
    var els = [document.getElementById("add-time"), document.getElementById("all-day")]
    var hideEls = document.getElementsByClassName("form-field-hideable")
    for (i = 0; i < hideEls.length; i++) {
      els.push(hideEls[i]);
    }
    for (i = 0; i < els.length; i++) {
      els[i].classList.toggle("form-field-hide")
    }
  }
  document.getElementById("add-time").addEventListener("click", hideFuncOne);

  // Function to toggle the form-field-hide class for all elements with form-field-hideable class,
  // adds the function to the all-day checkbox
  function hideFuncTwo() {
    var els = document.getElementsByClassName("form-field-hideable")
    for (i = 0; i < els.length; i++) {
      els[i].classList.toggle("form-field-hide")
    }
  }
  document.getElementById("id_all_day").addEventListener("click", hideFuncTwo);

  // Clears the time fields, adds the function to the all-day checkbox
  function clearTimes() {
    var el = document.getElementById("id_start_time")
    el.value = ""
    var el = document.getElementById("id_end_time")
    el.value = ""
  }
  document.getElementById("id_all_day").addEventListener("click", clearTimes);

  // Clears the enddate field, adds the function to the add-time button
  function clearEndDate() {
    var el = document.getElementById("id_end_date")
    el.value = ""
  }
  document.getElementById("add-time").addEventListener("click", clearEndDate);

  
  // JS to control the two dropdown menu's to select parent category and category
  //
  //
  // Gets the category select element by id
  var cat_select = document.getElementById("id_category")
  // Hides the category by default
  cat_select.classList.add("hide");

  // Gets the parent category select element by id
  var par_cat_select = document.getElementById("id_parent_category")
  // Shows the category select once the parent category select has changed input
  par_cat_select.addEventListener("input", function () {
    $("#id_category").removeClass("hide");
  });
  // Hides all categories
  par_cat_select.addEventListener("input", function () { 
    hide_categories();
  });
  // Shows the categories related to the parent category
  par_cat_select.addEventListener("input", function () {
    show_categories(par_cat_select.value); 
  });
  // Clears the category field when parent category changes
  par_cat_select.addEventListener("input", function () {
    cat_select.value = ""
  });

  // Hides all the category options by iterating through all options in the select element and setting 
  // their disabled and hidden attributes to true
  function hide_categories () {
    for (i = 0; i < cat_select.options.length; i++) {
      cat_select.options[i].disabled = true;
      cat_select.options[i].hidden = true;
    };
  };
  
  // Takes the categories from the django view with a template tag
  // and takes the parent category pk as input
  function show_categories (p_pk) {
    const filtered_cats = filter_categories('{{categories|safe}}', Number(p_pk));

    // Iterates through all the category select options to check if they exist in the filtered categories list
    // If so, removes the disabled and hidden attributes so that the option shows in the select element
    for (j = 0; j < cat_select.options.length; j++) {
      if (filtered_cats.includes(cat_select.options[j].label)) {
        cat_select.options[j].disabled = false;
        cat_select.options[j].hidden = false;
      }   
    };
  };

  // Takes in a JSON and the parent pk from the parent category select element to filter what categories should be visible
  function filter_categories (cat, p_pk) {
    // Parses the JSON
    const cat_parsed = JSON.parse(cat)
    // Filters the JSON based on the parent pk
    const cat_filtered = cat_parsed.filter(function (category) {
      return category.fields.parent_category===p_pk;
    });
    
    // Turns the filtered categories dictionary into a list
    const cat_list = []
    for (i = 0; i < cat_filtered.length; i++) {
      cat_list.push(cat_filtered[i].fields.name)
    };
    return cat_list
  };

  // Takes the category select value and transfers this to the title text input
  cat_select.addEventListener("input", function () {
    document.getElementById("id_title").value = this.options[this.selectedIndex].label;
  });

  // Hides the planned exertion form field unless the category is 'Training'
  var planned_exertion = document.getElementById("planned_exertion")
  planned_exertion.classList.add("hide")

  par_cat_select.addEventListener("input", function () {
    if (this.options[this.selectedIndex].label === "Training") {
      planned_exertion.classList.remove("hide")
    } else {
      planned_exertion.classList.add("hide")
    };
  });


  // Add new category option in the parent category select element redirects to the create category url
  $(function(){
      // bind change event to select
      $('#id_parent_category').on('change', function () {
          var url = $(this).val(); // get selected value
          if (url.length > 3) { // checks the length of the url so that it is longer than just a category pk
              window.location = url; // redirect
          }
          return false;
      });
    });
</script>

templates/calendarapp/event_delete.html
<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header bg-primary">
    <h5 class="modal-title text-white">Delete Event</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body" style="height: 120px">
    <p>Are you sure you want to delete this event?</p>
    <button class="btn btn-danger" type="submit">Confirm</button>
    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
  </div>

  <div class="modal-footer"></div>

</form>

templates/calendarapp/exercise.html
<form method="post" action="">
  {% csrf_token %}

 <div class="modal-header bg-primary">
    <h5 class="modal-title text-white">Create Exercise</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body" style="height: 80vh; overflow-y: auto;">
    <div class="form-group">
      {{ form.event }}
    </div>
    <div class="form-group">
      {{ form.category }}
    </div>
    <div class="form-group">
      <h6 class="d-inline align-middle" style="margin-right: 10px;">Reps</h6>{{ form.reps }}
    </div>
    <div class="form-group">
      <h6 class="d-inline align-middle" style="margin-right: 10px;">Duration (s)</h6>{{ form.duration }}
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create</button>
  </div>

</form>