accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

calendarapp/urls.py
from django.urls import path

from . import views

app_name = "calendarapp"


urlpatterns = [
    path("", views.CalendarView.as_view(), name="calendar"),
    path("evaluation/", views.OverviewView.as_view(), name="overview"),
    path("event/new/", views.EventModalCreateView.as_view(), name="event"),
    path(
        "event/new/<str:date>/",
        views.EventModalCreateView.as_view(),
        name="event_create",
    ),
    path(
        "event/details/<int:pk>/",
        views.EventDetailsModalUpdateView.as_view(),
        name="event_details",
    ),
    path(
        "event/edit/<int:pk>/",
        views.EventEditModalUpdateView.as_view(),
        name="event_edit",
    ),
    path(
        "event/post_edit/<int:pk>/",
        views.EventPostEditModalUpdateView.as_view(),
        name="event_post_edit",
    ),
    path(
        "event/remove/<int:pk>/",
        views.EventDeleteModalUpdateView.as_view(),
        name="event_delete",
    ),
    path(
        "eventcategory/new/",
        views.EventCategoryCreateView.as_view(),
        name="eventcategory_create",
    ),
    path("all-events-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "upcoming-events-list/",
        views.UpcomingEventsListView.as_view(),
        name="upcoming_events",
    ),
    path("exercises-list/", views.AllExercisesListView.as_view(), name="exercises"),
    path("exercise/new/", views.ExerciseModalCreateView.as_view(), name="exercise"),
]

templates/base/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
                content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta name="mobile-web-app-capable" content="yes">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}{% endblock title %}EquDiary</title>
        <link rel="icon" type="image/png" sizes="512x512" href="{% static 'images/favicons/favicon-512x512.png' %}">
        <link rel="icon" type="image/png" sizes="192x192" href="{% static 'images/favicons/favicon-192x192.png' %}">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/favicon-180x180.png' %}">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicons/favicon-96x96.png' %}">
        <link rel="icon" type="image/png" sizes="48x48" href="{% static 'images/favicons/favicon-48x48.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">

        <!-- Main CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}?r={{ rand }}">
        <!-- Font-icon CSS-->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- Extra CSS-->
        {% block extracss %}
        {% endblock extracss %}
    </head>
    <body class="app sidebar-mini">
        <!-- Navbar-->
        <header class="app-header">
            <a class="app-header__logo" href="{% url 'calendarapp:calendar' %}"><img src="{% static 'images/favicons/favicon-180x180.png' %}" width="32px" style="padding-bottom: 10px;" alt=""> EquDiary</a>
            <!-- Sidebar toggle button-->
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
            <!-- Navbar Right Menu-->
            <ul class="app-nav">
                <!-- User Menu-->
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
                    <ul class="dropdown-menu settings-menu dropdown-menu-right">
                        <li>
                            <a class="dropdown-item" href="{% url 'accounts:signout' %}"><i class="fa fa-sign-out fa-lg"></i> Sign Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </header>
        <!-- Sidebar menu-->
        <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        <aside class="app-sidebar">
            <ul class="app-menu">
                <li>
                    <a class="app-menu__item {% if request.resolver_match.url_name == 'calendar' %} active{% endif %}" href="{% url 'calendarapp:calendar' %}"><i class="app-menu__icon fa fa-calendar"></i><span class="app-menu__label">Calendar</span></a>
                </li>
                <li>
                    <a class="app-menu__item {% if request.resolver_match.url_name == 'overview' %} active{% endif %}" href="{% url 'calendarapp:overview' %}"><i class="app-menu__icon fa fa-commenting-o"></i><span class="app-menu__label">Evaluation</span></a>
                </li>
                <li class="treeview">
                    <a class="app-menu__item {% if request.resolver_match.url_name == 'upcoming_events' or request.resolver_match.url_name == 'all_events' %} active{% endif %}" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Events</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                    <ul class="treeview-menu">
                        <li>
                            <a class="treeview-item" href="{% url 'calendarapp:upcoming_events' %}"><i class="icon fa fa-circle-o"></i> Upcoming</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'calendarapp:all_events' %}"><i class="icon fa fa-circle-o"></i> All</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a class="app-menu__item {% if request.resolver_match.url_name == 'exercises-list' %} active{% endif %}" href="{% url 'calendarapp:exercises' %}"><i class="app-menu__icon fa fa-line-chart"></i><span class="app-menu__label">Exercises</span></a>
                </li>
            </ul>
        </aside>
        <main class="app-content">
            {% block content %}
            {% endblock content %}
        </main>
        <!-- Essential javascripts for application to work-->
        {% include 'base/js.html' %}
        {% block extrascripts %}
        {% endblock extrascripts %}
    </body>
</html>

templates/base/js.html
{% load static %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- The javascript plugin to display page loading on top-->
<script src="{% static 'js/plugins/pace.min.js'%}"></script>
<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>